-- MySQL Script generated by MySQL Workbench
-- Mon May 20 10:48:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ISY-CF
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ISY-CF` ;

-- -----------------------------------------------------
-- Schema ISY-CF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISY-CF` DEFAULT CHARACTER SET utf8 ;
USE `ISY-CF` ;

-- -----------------------------------------------------
-- Table `ISY-CF`.`Vehicle_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Vehicle_Type` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Vehicle_Type` (
  `Vehicle_Type_ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(120) NULL,
  PRIMARY KEY (`Vehicle_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Vehicle` (
  `Vehicle_ID` INT NOT NULL AUTO_INCREMENT,
  `Registration` VARCHAR(12) NULL,
  `Description` VARCHAR(120) NULL,
  `Type` INT NOT NULL,
  `Decommissioned` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Vehicle_ID`),
  CONSTRAINT `fk_Vehicle_Vehicle_Type`
    FOREIGN KEY (`Type`)
    REFERENCES `ISY-CF`.`Vehicle_Type` (`Vehicle_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vehicle_Vehicle_Type_idx` ON `ISY-CF`.`Vehicle` (`Type` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Fuel_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Fuel_Type` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Fuel_Type` (
  `Fuel_Type_ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(30) NULL,
  PRIMARY KEY (`Fuel_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Fuel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Fuel` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Fuel` (
  `Fuel_ID` INT NOT NULL AUTO_INCREMENT,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Type` INT NOT NULL,
  `Amount` INT NOT NULL,
  `Vehicle_ID` INT NOT NULL,
  PRIMARY KEY (`Fuel_ID`),
  CONSTRAINT `fk_Fuel_Vehicle1`
    FOREIGN KEY (`Vehicle_ID`)
    REFERENCES `ISY-CF`.`Vehicle` (`Vehicle_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fuel_Fuel_Type1`
    FOREIGN KEY (`Type`)
    REFERENCES `ISY-CF`.`Fuel_Type` (`Fuel_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fuel_Vehicle1_idx` ON `ISY-CF`.`Fuel` (`Vehicle_ID` ASC);

CREATE INDEX `fk_Fuel_Fuel_Type1_idx` ON `ISY-CF`.`Fuel` (`Type` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Bus` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Bus` (
  `Bus_ID` INT NOT NULL AUTO_INCREMENT,
  `Number_of_Buses` INT NULL,
  `Distance` INT NULL,
  PRIMARY KEY (`Bus_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Flight_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Flight_Type` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Flight_Type` (
  `Flight_Type_ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Flight_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Flight` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Flight` (
  `Flight_ID` INT NOT NULL AUTO_INCREMENT,
  `Type` INT NOT NULL,
  `Distance` INT NOT NULL,
  PRIMARY KEY (`Flight_ID`),
  CONSTRAINT `fk_Flight_Flight_Type1`
    FOREIGN KEY (`Type`)
    REFERENCES `ISY-CF`.`Flight_Type` (`Flight_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Flight_Flight_Type1_idx` ON `ISY-CF`.`Flight` (`Type` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Trip_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Trip_Group` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Trip_Group` (
  `Trip_Group_ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`Trip_Group_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Trip` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Trip` (
  `Trip_ID` INT NOT NULL AUTO_INCREMENT,
  `Group` INT NOT NULL,
  `Bus_Bus_ID` INT NULL,
  `Flight_Flight_ID` INT NULL,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Number_of_people` INT NULL,
  PRIMARY KEY (`Trip_ID`),
  CONSTRAINT `fk_Trip_Bus1`
    FOREIGN KEY (`Bus_Bus_ID`)
    REFERENCES `ISY-CF`.`Bus` (`Bus_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trip_Flight1`
    FOREIGN KEY (`Flight_Flight_ID`)
    REFERENCES `ISY-CF`.`Flight` (`Flight_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trip_Group1`
    FOREIGN KEY (`Group`)
    REFERENCES `ISY-CF`.`Trip_Group` (`Trip_Group_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Trip_Bus1_idx` ON `ISY-CF`.`Trip` (`Bus_Bus_ID` ASC);

CREATE INDEX `fk_Trip_Flight1_idx` ON `ISY-CF`.`Trip` (`Flight_Flight_ID` ASC);

CREATE INDEX `fk_Trip_Trip_Group1_idx` ON `ISY-CF`.`Trip` (`Group` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Electricity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Electricity` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Electricity` (
  `Electricity_ID` INT NOT NULL AUTO_INCREMENT,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Meter_Units` INT NULL,
  PRIMARY KEY (`Electricity_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Generator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Generator` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Generator` (
  `Generator_ID` INT NOT NULL AUTO_INCREMENT,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`Generator_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`AC_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`AC_Type` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`AC_Type` (
  `AC_Type_ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(60) NOT NULL,
  `Number` INT NOT NULL,
  PRIMARY KEY (`AC_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`AC_coolant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`AC_coolant` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`AC_coolant` (
  `AC_Coolant_ID` INT NOT NULL AUTO_INCREMENT,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`AC_Coolant_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`AC_Consumables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`AC_Consumables` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`AC_Consumables` (
  `AC_Type_ID` INT NOT NULL,
  `AC_Coolant_ID` INT NOT NULL,
  PRIMARY KEY (`AC_Type_ID`, `AC_Coolant_ID`),
  CONSTRAINT `fk_AC_Consumables_AC_Type1`
    FOREIGN KEY (`AC_Type_ID`)
    REFERENCES `ISY-CF`.`AC_Type` (`AC_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AC_Consumables_AC_coolant1`
    FOREIGN KEY (`AC_Coolant_ID`)
    REFERENCES `ISY-CF`.`AC_coolant` (`AC_Coolant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AC_Consumables_AC_coolant1_idx` ON `ISY-CF`.`AC_Consumables` (`AC_Coolant_ID` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Waste_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Waste_Type` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Waste_Type` (
  `Waste_Type_ID` INT NOT NULL,
  `Description` VARCHAR(80) NOT NULL,
  `Capacity` INT NOT NULL,
  `Total` INT NOT NULL,
  PRIMARY KEY (`Waste_Type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Waste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Waste` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Waste` (
  `Waste_ID` INT NOT NULL,
  `Type` INT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`Waste_ID`),
  CONSTRAINT `fk_Waste_Waste_Type1`
    FOREIGN KEY (`Type`)
    REFERENCES `ISY-CF`.`Waste_Type` (`Waste_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Waste_Waste_Type1_idx` ON `ISY-CF`.`Waste` (`Type` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`Paper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Paper` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Paper` (
  `Paper_ID` INT NOT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `A4_Reams` INT NOT NULL,
  `A3_Reams` INT NOT NULL,
  PRIMARY KEY (`Paper_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Meat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Meat` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Meat` (
  `Meat_ID` INT NOT NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`Meat_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISY-CF`.`Year_Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`Year_Book` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`Year_Book` (
  `YearBook_ID` INT NOT NULL,
  `Year` DATE NULL,
  `Paper_Paper_ID` INT NOT NULL,
  PRIMARY KEY (`YearBook_ID`),
  CONSTRAINT `fk_Year_Book_Paper1`
    FOREIGN KEY (`Paper_Paper_ID`)
    REFERENCES `ISY-CF`.`Paper` (`Paper_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Year_Book_Paper1_idx` ON `ISY-CF`.`Year_Book` (`Paper_Paper_ID` ASC);


-- -----------------------------------------------------
-- Table `ISY-CF`.`AC_CO2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ISY-CF`.`AC_CO2` ;

CREATE TABLE IF NOT EXISTS `ISY-CF`.`AC_CO2` (
  `Start_Date` DATE NOT NULL,
  `Multiplier` INT NULL,
  `AC_Type_AC_Type_ID` INT NOT NULL,
  PRIMARY KEY (`Start_Date`, `AC_Type_AC_Type_ID`),
  CONSTRAINT `AC_Type_ID`
    FOREIGN KEY (`AC_Type_AC_Type_ID`)
    REFERENCES `ISY-CF`.`AC_Type` (`AC_Type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AC_CO2_AC_Type1_idx` ON `ISY-CF`.`AC_CO2` (`AC_Type_AC_Type_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
